import { Token } from "../db";

export const initialTokens: Token[] = [
  {
    address: "So11111111111111111111111111111111111111112",
    symbol: "SOL",
    name: "Wrapped SOL",
    decimals: 9,
    iconUrl: "/tokens/SOL.png",
  },
  {
    address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    symbol: "USDC",
    name: "USD Coin",
    decimals: 6,
    iconUrl: "/tokens/USDC.png",
  },
  {
    address: "6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN",
    symbol: "TRUMP",
    name: "OFFICIAL TRUMP",
    decimals: 6,
    iconUrl: "/tokens/TRUMP.png",
  },
  {
    address: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
    symbol: "JUP",
    name: "Jupiter",
    decimals: 6,
    iconUrl: "/tokens/JUP.png",
  },
  {
    address: "EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm",
    symbol: "WIF",
    name: "dogwifhat",
    decimals: 6,
    iconUrl: "/tokens/WIF.png",
  },
  {
    address: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
    symbol: "BONK",
    name: "Bonk",
    decimals: 5,
    iconUrl: "/tokens/BONK.png",
  },
  {
    address: "jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL",
    symbol: "JTO",
    name: "Jito",
    decimals: 9,
    iconUrl: "/tokens/JTO.png",
  },
  {
    address: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
    symbol: "RAY",
    name: "Raydium",
    decimals: 6,
    iconUrl: "/tokens/RAY.png",
  },
  {
    address: "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3",
    symbol: "PYTH",
    name: "Pyth Network",
    decimals: 6,
    iconUrl: "/tokens/PYTH.png",
  },
  {
    address: "hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux",
    symbol: "HNT",
    name: "Helium Network Token",
    decimals: 6,
    iconUrl: "/tokens/HNT.png",
  },
  {
    address: "85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ",
    symbol: "W",
    name: "Wormhole",
    decimals: 6,
    iconUrl: "/tokens/W.png",
  },
  {
    address: "MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5",
    symbol: "MEW",
    name: "cat in a dogs world",
    decimals: 6,
    iconUrl: "/tokens/MEW.png",
  },
  {
    address: "7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr",
    symbol: "POPCAT",
    name: "Popcat (SOL)",
    decimals: 9,
    iconUrl: "/tokens/POPCAT.png",
  },
  {
    address: "orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE",
    symbol: "ORCA",
    name: "Orca",
    decimals: 6,
    iconUrl: "/tokens/ORCA.png",
  },
  {
    address: "ZEUS1aR7aX8DFFJf5QjWj2ftDDdNTroMNGo8YoQm3Gq",
    symbol: "ZEUS",
    name: "Zeus Network",
    decimals: 6,
    iconUrl: "/tokens/ZEUS.png",
  },
  {
    address: "KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS",
    symbol: "KMNO",
    name: "Kamino",
    decimals: 6,
    iconUrl: "/tokens/KMNO.png",
  },
  {
    address: "9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E",
    symbol: "WBTC",
    name: "Wrapped Bitcoin (Portal)",
    decimals: 8,
    iconUrl: "/tokens/WBTC.png",
  },
  {
    address: "jupSoLaHXQiZZTSfEWMTRRgpnyFm8f6sZdosWBjx93v",
    symbol: "jupSOL",
    name: "Jupiter Staked SOL",
    decimals: 9,
    iconUrl: "/tokens/jupSOL.png",
  },
  {
    address: "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn",
    symbol: "JitoSOL",
    name: "Jito Staked SOL",
    decimals: 9,
    iconUrl: "/tokens/JitoSOL.png",
  },
  {
    address: "5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm",
    symbol: "INF",
    name: "Infinity",
    decimals: 9,
    iconUrl: "/tokens/INF.png",
  },
  {
    address: "bioJ9JTqW62MLz7UKHU69gtKhPpGi1BQhccj2kmSvUJ",
    symbol: "BIO",
    name: "BIO",
    decimals: 6,
    iconUrl: "/tokens/BIO.png",
  },
  {
    address: "LAYER4xPpTCb3QL8S9u41EAhAX7mhBn8Q6xMTwY2Yzc",
    symbol: "LAYER",
    name: "Solayer",
    decimals: 6,
    iconUrl: "/tokens/LAYER.png",
  },
  {
    address: "14zP2ToQ79XWvc7FQpm4bRnp9d6Mp1rFfsUW3gpLcRX",
    symbol: "AIXBT",
    name: "aixbt by Virtuals (Wormhole)",
    decimals: 6,
    iconUrl: "/tokens/AIXBT.png",
  },
  {
    address: "GJAFwWjJ3vnTsrQVabjBVK2TYB1YtRCQXRDfDgUnpump",
    symbol: "ACT",
    name: "Act I : The AI Prophecy",
    decimals: 6,
    iconUrl: "/tokens/ACT.png",
  },
  {
    address: "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump",
    symbol: "Fartcoin",
    name: "Fartcoin",
    decimals: 6,
    iconUrl: "/tokens/Fartcoin.png",
  },
  {
    address: "FUAfBo2jgks6gB4Z4LfZkqSZgzNucisEHqnNebaRxM1P",
    symbol: "MELANIA",
    name: "MELANIA",
    decimals: 6,
    iconUrl: "/tokens/MELANIA.png",
  },
];
